from __future__ import annotations

APP_NAME = "WechatLocalChatAnalysis"
SCHEMA_VERSION = 1

DEFAULT_CAPTURE_COUNT = 10
DEFAULT_SCROLL_CLICKS = -5
DEFAULT_DELAY_SECONDS = 0.6
DEFAULT_PRE_CAPTURE_DELAY_SECONDS = 3.0
DEFAULT_MIN_CONFIDENCE = 0.85
DEFAULT_LEFT_SPEAKER_THRESHOLD = 0.45
DEFAULT_RIGHT_SPEAKER_THRESHOLD = 0.55

SUPPORTED_IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg"}

